export const cursos = [
  {
    id: "oratoria",
    slotDia: "SÁBADOS",
    slotHora: "6 sessões · 4h/sessão",
    titulo: "Comunicação Assertiva e Oratória",
    resumo: "Fale com clareza, confiança e impacto.",
    lede: "Desenvolva a segurança e a estrutura para falar bem em público, em entrevistas, reuniões e apresentações.",
    paraQuem:
      "Jovens e profissionais que precisam de comunicar com mais segurança em público — em entrevistas, reuniões, aulas ou apresentações de trabalho.",
    modulos: [
      "Fundamentos da comunicação assertiva",
      "Controlo do medo de falar em público",
      "Voz, respiração e postura",
      "Estrutura de discursos e argumentação",
      "Prática de oratória com feedback filmado",
      "Simulação final: discurso avaliado",
    ],
    duracao: "6 sábados",
    formato: "Presencial, em parceria",
    local: "Instituição parceira, Luanda",
    data: "4 de Outubro",
    vagasTotal: 25,
    vagasRestantes: 14,
  },
  {
    id: "empreendedorismo",
    slotDia: "DOMINGOS",
    slotHora: "5 sessões · 4h/sessão",
    titulo: "Empreendedorismo e Educação Financeira",
    resumo: "Transforme ideias em negócios e organize as suas finanças.",
    lede: "Da ideia ao plano de negócio, passando pela organização financeira pessoal e do negócio.",
    paraQuem:
      "Jovens empreendedores, autónomos e quem quer sair da informalidade com um negócio mais organizado.",
    modulos: [
      "Mentalidade empreendedora",
      "Como validar uma ideia de negócio",
      "Educação financeira pessoal",
      "Gestão financeira de pequenos negócios",
      "Elaboração de um plano de negócio simples",
    ],
    duracao: "5 domingos",
    formato: "Presencial, em parceria",
    local: "Instituição parceira, Luanda",
    data: "11 de Outubro",
    vagasTotal: 30,
    vagasRestantes: 20,
  },
  {
    id: "marketing",
    slotDia: "SÁBADOS",
    slotHora: "6 sessões · 4h/sessão",
    titulo: "Marketing Digital e Marca Pessoal",
    resumo: "Construa a sua marca e venda com estratégia nas redes.",
    lede: "Estratégia, conteúdo e comunicação persuasiva para se tornar mais visível online.",
    paraQuem:
      "Criadores de conteúdo, freelancers, pequenos negócios e profissionais que querem mais visibilidade online.",
    modulos: [
      "Fundamentos do marketing digital",
      "Redes sociais e conteúdo estratégico",
      "Construção de marca pessoal",
      "Copywriting e comunicação persuasiva",
      "Métricas e ferramentas essenciais",
      "Projecto prático: plano de marca pessoal",
    ],
    duracao: "6 sábados",
    formato: "Presencial, em parceria",
    local: "Instituição parceira, Luanda",
    data: "18 de Outubro",
    vagasTotal: 25,
    vagasRestantes: 25,
  },
  {
    id: "gestao-projectos",
    slotDia: "DOMINGOS",
    slotHora: "5 sessões · 4h/sessão",
    titulo: "Gestão de Projectos",
    resumo: "Planeie, execute e entregue projectos com método.",
    lede: "Ferramentas práticas de planeamento, equipa e risco para levar projectos até ao fim.",
    paraQuem:
      "Profissionais, estudantes finalistas e empreendedores que lideram ou querem liderar projectos.",
    modulos: [
      "Fundamentos da gestão de projectos",
      "Planeamento e cronograma",
      "Gestão de equipas e comunicação",
      "Gestão de riscos e recursos",
      "Projecto prático com apresentação final",
    ],
    duracao: "5 domingos",
    formato: "Presencial, em parceria",
    local: "Instituição parceira, Luanda",
    data: "25 de Outubro",
    vagasTotal: 20,
    vagasRestantes: 9,
  },
  {
    id: "tv-radio",
    slotDia: "SÁBADOS",
    slotHora: "6 sessões · 4h/sessão",
    titulo: "Técnicas de Apresentação em Televisão e Rádio",
    resumo: "Prepare-se para estar diante da câmara e do microfone.",
    lede: "Voz, presença e naturalidade para apresentar, entrevistar e improvisar com confiança.",
    paraQuem:
      "Aspirantes a apresentador, jornalista, locutor ou criador de conteúdo em vídeo.",
    modulos: [
      "Linguagem televisiva e radiofónica",
      "Dicção, voz e presença",
      "Leitura de teleponto e naturalidade",
      "Entrevistas e improviso",
      "Prática em estúdio parceiro",
      "Gravação final para portfólio",
    ],
    duracao: "6 sábados",
    formato: "Presencial, em parceria",
    local: "Estúdio parceiro, Luanda",
    data: "1 de Novembro",
    vagasTotal: 20,
    vagasRestantes: 20,
  },
];
